## Goose update
---
Simple tool writen in go, refresh timestamp migration script generated by [goose](https://bitbucket.org/liamstask/goose).

### Common problem

When we generate many migrations we can update our migrations with the goose command:

``$ goose up``

```
$ goose: migrating db environment 'development', current version: 0, target: 3
$ OK    2014112901_basics.sql
$ OK    2014112902_next.sql
$ OK    2014112903_and_again.go
```

But, what's the matter when our team create another bunch script?

We can have dependences or maybe we have constraints to update. In this case a goose update is necesary:

```
$ update -path="db/migrations/team/"
$ OK    2014112904_create_table.sql
$ OK    2014112907_add_contraints.sql
$ OK    2014112910_clean_db.go
```
